name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag interview-image:latest
    - name: Spin up container
      run: docker run -d --name interview-container -p 80:80 interview-image:latest
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
